### ISSUE TITLE
Bug: Adding tags causes compile error.

### ISSUE THREAD

**Issue by ollydixon** [jlalmes/trpc-openapi#215]
Example API

```
import { nanoid } from 'nanoid';
import { z } from 'zod';
import { ApiTags } from './openapi';
import { publicProcedure } from './trpc';

export const health = publicProcedure
  .meta({ openapi: { method: 'POST', path: '/health', tags: [ApiTags.admin] } })
  .input(
    z.void(),
    //
  )
  .output(
    z.object({
      status: z.string(),
    }),
  )
  .mutation(async ({ ctx, input }) => {
    return { status: nanoid(9) };
  });
```
```
Example of init

import { generateOpenApiDocument } from 'trpc-openapi';
import { appRouter } from './routes';

export const ApiTags = {
  admin: 'admin',
  auth: 'auth',
};

export const openApiDocument = generateOpenApiDocument(appRouter, {
  title: 'tRPC OpenAPI',
  description: 'API',
  version: '1.0.0',
  baseUrl: `http://localhost:${process.env.PORT ?? 8080}/trpc`,
  tags: [
    ApiTags.admin,
    ApiTags.auth,
    //
  ],
});

```

The error

```
TypeError: Cannot read properties of undefined (reading '_def')
    at getOpenApiPathsObject (/Users/oliverdixon/Projects/app/node_modules/trpc-openapi/src/generator/paths.ts:14:32)
    at generateOpenApiDocument (/Users/oliverdixon/Projects/app/node_modules/trpc-openapi/src/generator/index.ts:34:33)
```

Using strings directly works.
So it's an issue with class inference?

**Comment by ollydixon** [comment]
Interestingly, if I try to export as a class I get the same error, hmm.

```
class ApiTagsClass {
  public admin: string = 'admin';
  public auth: string = 'auth';
}

const ApiTags = new ApiTagsClass();
export { ApiTags };
```

**Comment by jlalmes** [comment]
Unable to reproduce.
https://stackblitz.com/edit/node-q7j8j2?file=index.ts

Can you make sure your `trpc` & `trpc-openapi` dependencies are up to date.
