### ISSUE TITLE
zod array objects break this

### ISSUE THREAD

**Issue by davidawad** [jlalmes/trpc-openapi#391]
heres' an example: 

<img width="726" alt="image" src="https://github.com/jlalmes/trpc-openapi/assets/4019054/3ff97ec5-7533-4327-9cab-ef683b66390c">

if I have this code defining a schema and try to make TRPC calls (on ANY API, not just this one), I'll get this error: 

```
error - TRPCError: [query.question.read] - Input parser key: "labels" must be ZodString, ZodNumber, ZodBoolean, ZodBigInt or ZodDate
    at /Users/david/Projects/WORK/DFDF/DDQ360/node_modules/trpc-openapi/dist/generator/schema.js:72:27
    at Array.map (<anonymous>)
    at getParameterObjects (/Users/david/Projects/WORK/DFDF/DDQ360/node_modules/trpc-openapi/dist/generator/schema.js:65:10)
    at /Users/david/Projects/WORK/DFDF/DDQ360/node_modules/trpc-openapi/dist/generator/paths.js:61:66
    at forEachOpenApiProcedure (/Users/david/Projects/WORK/DFDF/DDQ360/node_modules/trpc-openapi/dist/utils/procedure.js:34:13)
    at getOpenApiPathsObject (/Users/david/Projects/WORK/DFDF/DDQ360/node_modules/trpc-openapi/dist/generator/paths.js:13:45)
    at generateOpenApiDocument (/Users/david/Projects/WORK/DFDF/DDQ360/node_modules/trpc-openapi/dist/generator/index.js:27:50)
    at eval (webpack-internal:///(api)/./src/server/api/root.ts:51:98)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'INTERNAL_SERVER_ERROR',
  [cause]: undefined
}
```

**Comment by Pridestalkerr** [comment]
I believe this happens because there is no "default" way to pass an array of values as a query parameter. It might work for tRPC, but there's no easy widely adopted method of passing arrays as a query parameter and most implementations are framework specific. Which one of the following endpoints should even be generated?
```
?cars[]=Saab&cars[]=Audi
?cars=Saab&cars=Audi
?cars=Saab,Audi
```
I suggest using a POST request instead and passing everything in the body. Alternatively, you can make "labels" into a string, and parse it manually (using the format you chose) inside the procedure. But that's a bit weird IMO.

**Comment by ntindle** [comment]
I've also been unable to use arrays in inputs for PUT. See #255

**Comment by tdanh2k** [comment]
![image](https://github.com/jlalmes/trpc-openapi/assets/60866158/0fa40381-cf2c-4b09-bc70-e5948f6fa8be)

![image](https://github.com/jlalmes/trpc-openapi/assets/60866158/3b9ef3ce-57c9-47b8-87f8-dcacf75f1cc3)
I'm building a pagination router with the above schema but also facing the same ordeal. Hope this get fixed soon :(

**Comment by tdanh2k** [comment]
> ![image](https://private-user-images.githubusercontent.com/60866158/316110020-0fa40381-cf2c-4b09-bc70-e5948f6fa8be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMjc3NzMsIm5iZiI6MTcxMTEyNzQ3MywicGF0aCI6Ii82MDg2NjE1OC8zMTYxMTAwMjAtMGZhNDAzODEtY2YyYy00YjA5LWJjNzAtZTU5NDhmNmZhOGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDE3MTExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyOTc3NzY1Y2Q1ZjQwNjk3OGYyNjdhYmNmNjNiZWY5ODFjZWJiYjVjMzQyMTRlZTZkZTY0M2I1OWI5MTc5OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o9QXGip-w_WGLvijZO33E-69enSHExpa_9aS93ZGnbE)
> 
> ![image](https://private-user-images.githubusercontent.com/60866158/316109462-3b9ef3ce-57c9-47b8-87f8-dcacf75f1cc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMjc3NzMsIm5iZiI6MTcxMTEyNzQ3MywicGF0aCI6Ii82MDg2NjE1OC8zMTYxMDk0NjItM2I5ZWYzY2UtNTdjOS00N2I4LTg3ZjgtZGNhY2Y3NWYxY2MzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDE3MTExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwNmI1MDdmNWExNmZjMzljYWNiNmRjMWMxODFlYjU0Yjc4OGU1MjdkYTk0MTJkMTk2MzRmNDM0NjlkMzEyYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WK9unBCAgsXWblsTvmcp3ggMuN-XnzRfeXxGCNsjMdE) I'm building a pagination router with the above schema but also facing the same ordeal. Hope this get fixed soon :(

![image](https://github.com/jlalmes/trpc-openapi/assets/60866158/02fcd30f-e224-4cfc-87e8-9fe93ae340c2)

Or maybe just comment the .meta() method and move on.

**Comment by Pridestalkerr** [comment]
> @Pridestalkerr
> 
> > I suggest using a POST request instead and passing everything in the body. Alternatively, you can make "labels" into a string, and parse it manually (using the format you chose) inside the procedure. But that's a bit weird IMO.
> 
> It kind of defeats the purpose of generating the openapi spec, doesn't it? If the document generated is not representing what is expected by the implementing code, what is it good for then?

@renke0 some clarifications.
Most REST specs do not support arrays in query parameters.
How would you even represent it? `/your/get/endpoint?array=["v1", "v2"]`
What if the array contains objects? Do you stringify them? At that point you probably just stringify the entire array. But then the query value of `array` will be string.
I'm sure there's frameworks that can do this on the fly and convert any query values from json strings to objects, but not tRPC.
Hence my suggestion to pass it in the body instead. GET requests can have a body, but AFAIK the REST spec says thats a bad idea and the request should be a POST instead (not my opinion).
This library generates a REST spec, and thus assumes that GET requests only receive query parameters, no body.

Please, do take this with a grain of salt. It's just what i learned back when I encountered this issue myself.
Best of luck!
