### ISSUE TITLE
Any plans to seek a new maintainer?

### ISSUE THREAD

**Issue by musjj** [jlalmes/trpc-openapi#451]
It looks like a year has passed since the last commit and @jlalmes is now focusing on other things according to the bio in his profile.

Are there any plans to pass down the project to a new maintainer? I'm really thankful for this project, but it's really a shame to see it slowly becoming incompatible with the ecosystem:

- https://github.com/jlalmes/trpc-openapi/issues/442
- https://github.com/jlalmes/trpc-openapi/issues/434

For now I'm making do by using:

- https://github.com/jlalmes/trpc-openapi/pull/315 for Next.js 14 support (you can vendor `src/adapters/fetch.ts` into your project)
- https://github.com/jlalmes/trpc-openapi/issues/434#issuecomment-1936587096 for tRPC v11 patch

I haven't tested them extensively, but they do work decently on my small projects.

**Comment by KiranMantha** [comment]
@musjj , add this one as well. Unable to generate openapi contract json due to updations on how a procedure defeinition is generated by @trpc/server
- https://github.com/jlalmes/trpc-openapi/issues/431

**Comment by kdy1** [comment]
@jlalmes Do you have time to review/merge PRs? If not, can I do it instead?


As a side note, I'm the creator of the SWC project and maintainer of next.js/turbopack, although I'll not use working hours for this.

**Comment by kdy1** [comment]
I forked it for now.

https://github.com/kdy1/trpc-openapi

npm package: `better-trpc-openapi`

**Comment by bompi88** [comment]
Also a popup package here: https://github.com/vercjames/package-trpc-swagger

**Comment by Westernwells** [comment]
> https://github.com/vercjames/package-trpc-swagger

Encountering this same issue right now

**Comment by Westernwells** [comment]
> @kdy1 I'm getting the following error when errors are thrown or malformed JSON is posted to one of the endpoints:
> 
> ```
> TypeError: router._def.getErrorShape is not a function
>     at ~/whatever/node_modules/.pnpm/better-trpc-openapi@0.1.0_@trpc+server@11.0.0-rc.477_zod@3.23.8/node_modules/better-trpc-openapi/src/adapters/node-http/core.ts:168:38
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async ~/whatever/node_modules/.pnpm/better-trpc-openapi@0.1.0_@trpc+server@11.0.0-rc.477_zod@3.23.8/node_modules/better-trpc-openapi/src/adapters/express.ts:18:5
> ```
> 
> Have you encountered this `TypeError` before and if so, what am I doing wrong here?


Encountering this same issue right now

**Comment by tristanz** [comment]
@kdy1 are you still interested in this?  @jlalmes do you have any thoughts?  I've love if we could organize a group of folks to maintain this actively.  Maybe we could do a brief huddle with 1-3 folks who are using this project in production and try to get a fork properly maintained.

**Comment by kdy1** [comment]
@tristanz Yes, I don't actively use my fork at the moment, but I'll need to expose my APIs in my private project in a near future.

**Comment by mcampa** [comment]
I have a fork that works with tRPC 11 https://www.npmjs.com/package/trpc-to-openapi

it's been running fine with t3-app/NextJS. However, I don't use other adapters, I fixed all tests cases for everything so in theory they should work. The only thing I couldn't port was the serverless adapter, the trpc implementation changed too much.

This is a fork of another fork (https://github.com/LilyRose2798/trpc-openapi) which uses `zod-openapi` instead of `zod-to-json-schema` and some other fixes.

**Comment by tayhalla** [comment]
@kdy1 are you actively maintaining your fork? If not, would you be open to us taking it over? We're going to be using it and committing to it.

**Comment by kdy1** [comment]
@tayhalla Of course. Are you going to maintain it as a team?

**Comment by rokitgg** [comment]
Is there any fork that works fine with NextJS app router? I've only found examples with the old pages router, and although the tRPC > OpenAPI conversion works fine, I've been struggling to set up a request handler using app router.

Thanks in advance!
